#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 20, 2018 11:22:03 AM


import sys
from tkinter import messagebox
from firebase import firebase as fb
from main.com.nnk.stocker import Stocker_Home
from firebase import firebase as fb


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def AddProduct_Save():
    print('Add_Product_support.AddProduct_Save')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def Product_No():
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/product", None)
    result = fire.get("product", None)
    if result is None:
        return "101"
    else:
        for x in result:
            pass
        no = int(x)
        no += 1
        return str(no)

def AddProduct_Save():
    no = Product_No()
    pno = w.AddProduct_Pno.get()
    pname = w.AddProduct_Name.get()
    pquantity = w.AddProduct_Quantity.get()
    price = w.AddProduct_Price.get()
    pname1 = re.search(r"\w+[a-zA-Z]",pname)
    pno1 = re.search(r"\w+[a-zA-Z0-9]",pno)
    pquantity1 = re.search(r"\w+[0-9]",pquantity)
    price1 = re.search(r"\w+[0-9]",price)
    if pno1 == "":
        messagebox.showerror("Add Product", "Please enter the product no.")
    elif pname1 == "":
        messagebox.showerror("Add Product", "Please enter the product name")
    elif pquantity1 == "":
        messagebox.showerror("Add Product", "Please enter the product quantity")
    elif price1 == "":
        messagebox.showerror("Add Product", "Please enter the price")
    elif pno1 == None:
        messagebox.showerror("Add Product", "Please enter proper product no.")
    elif pname1 == None:
        messagebox.showerror("Add Product", "Please enter proper product named")
    elif pquantity1 == None:
        messagebox.showerror("Add Product", "Please enter proper product quantity")
    elif price1 == None:
        messagebox.showerror("Add Product", "Please enter proper price")
    else:
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/product", None)
        fire.put("product", no, {"pname": pname, "pno": pno, "quantity": int(pquantity), "price": float(price)})
        messagebox.showinfo("Add Product", "Product is saved")


def AddProduct_Back():
    destroy_window()
    Stocker_Home.vp_start_gui()

if __name__ == '__main__':
    import Add_Product
    Add_Product.vp_start_gui()


