#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 20, 2018 11:23:08 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from  main.com.nnk.stocker import Add_Product_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Add_Product (root)
    Add_Product_support.init(root, top)
    root.mainloop()

w = None
def create_Add_Product(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Add_Product (w)
    Add_Product_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Add_Product():
    global w
    w.destroy()
    w = None


class Add_Product:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 20 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 14 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        top.geometry("538x603+650+150")
        top.title("Add_Product")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.02, relheight=0.97, relwidth=0.96)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(width=515)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.23, rely=0.05, height=46, width=282)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Add Product''')
        self.Label1.configure(width=282)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.1, rely=0.22, height=36, width=102)
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''PNO :''')
        self.Label2.configure(width=102)

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.08, rely=0.32, height=36, width=102)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font11)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name :''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.02, rely=0.43, height=36, width=132)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Quantity :''')
        self.Label2_2.configure(width=132)

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.08, rely=0.53, height=36, width=102)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#c4632b")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font11)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Price :''')

        self.AddProduct_Pno = Entry(self.Frame1)
        self.AddProduct_Pno.place(relx=0.29, rely=0.22, height=34, relwidth=0.47)

        self.AddProduct_Pno.configure(background="white")
        self.AddProduct_Pno.configure(disabledforeground="#a3a3a3")
        self.AddProduct_Pno.configure(font="TkFixedFont")
        self.AddProduct_Pno.configure(foreground="#000000")
        self.AddProduct_Pno.configure(insertbackground="black")
        self.AddProduct_Pno.configure(width=244)

        self.AddProduct_Name = Entry(self.Frame1)
        self.AddProduct_Name.place(relx=0.29, rely=0.32, height=34
                , relwidth=0.47)
        self.AddProduct_Name.configure(background="white")
        self.AddProduct_Name.configure(disabledforeground="#a3a3a3")
        self.AddProduct_Name.configure(font="TkFixedFont")
        self.AddProduct_Name.configure(foreground="#000000")
        self.AddProduct_Name.configure(highlightbackground="#d9d9d9")
        self.AddProduct_Name.configure(highlightcolor="black")
        self.AddProduct_Name.configure(insertbackground="black")
        self.AddProduct_Name.configure(selectbackground="#c4c4c4")
        self.AddProduct_Name.configure(selectforeground="black")

        self.AddProduct_Quantity = Entry(self.Frame1)
        self.AddProduct_Quantity.place(relx=0.29, rely=0.43, height=34
                , relwidth=0.47)
        self.AddProduct_Quantity.configure(background="white")
        self.AddProduct_Quantity.configure(disabledforeground="#a3a3a3")
        self.AddProduct_Quantity.configure(font="TkFixedFont")
        self.AddProduct_Quantity.configure(foreground="#000000")
        self.AddProduct_Quantity.configure(highlightbackground="#d9d9d9")
        self.AddProduct_Quantity.configure(highlightcolor="black")
        self.AddProduct_Quantity.configure(insertbackground="black")
        self.AddProduct_Quantity.configure(selectbackground="#c4c4c4")
        self.AddProduct_Quantity.configure(selectforeground="black")

        self.AddProduct_Price = Entry(self.Frame1)
        self.AddProduct_Price.place(relx=0.29, rely=0.53, height=34
                , relwidth=0.47)
        self.AddProduct_Price.configure(background="white")
        self.AddProduct_Price.configure(disabledforeground="#a3a3a3")
        self.AddProduct_Price.configure(font="TkFixedFont")
        self.AddProduct_Price.configure(foreground="#000000")
        self.AddProduct_Price.configure(highlightbackground="#d9d9d9")
        self.AddProduct_Price.configure(highlightcolor="black")
        self.AddProduct_Price.configure(insertbackground="black")
        self.AddProduct_Price.configure(selectbackground="#c4c4c4")
        self.AddProduct_Price.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.31, rely=0.65, height=43, width=86)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Add_Product_support.AddProduct_Save)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')
        self.Button1.configure(width=86)

        self.Button1_7 = Button(self.Frame1)
        self.Button1_7.place(relx=0.58, rely=0.65, height=43, width=86)
        self.Button1_7.configure(activebackground="#d9d9d9")
        self.Button1_7.configure(activeforeground="#000000")
        self.Button1_7.configure(background="#d9d9d9")
        self.Button1_7.configure(command=Add_Product_support.AddProduct_Back)
        self.Button1_7.configure(disabledforeground="#a3a3a3")
        self.Button1_7.configure(font=font11)
        self.Button1_7.configure(foreground="#000000")
        self.Button1_7.configure(highlightbackground="#d9d9d9")
        self.Button1_7.configure(highlightcolor="black")
        self.Button1_7.configure(pady="0")
        self.Button1_7.configure(text='''Back''')






if __name__ == '__main__':
    vp_start_gui()



