#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 21, 2018 10:49:14 PM


import sys
from tkinter import messagebox
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def ChangePassword():
    print('Change_Password_support.ChangePassword')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def variable(u):
    global d
    d = u

def ChangePassword():
    old = w.OldPassword.get()
    new = w.NewPassword.get()
    confirm = w.ConfirmPassword.get()
    from firebase import firebase as fb
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/stocker",None)
    result = fire.get("stocker",d)
    if old == "":
        messagebox.showerror("Change Password","Enter the old password")
    elif new == "":
        messagebox.showerror("Change Password", "Enter the new password")
    elif confirm == "":
        messagebox.showerror("Change Password", "Enter the confirm password")
    else:
        if result["pass"] == old and new == confirm:
            fire.put("stocker", d, {"name": result["name"], "cno": result["cno"], "pass": new})
            messagebox.showerror("Change Password", "Password is changed")
        else:
            messagebox.showerror("Change Password", "Invalid old password")



if __name__ == '__main__':
    import Change_Password
    Change_Password.vp_start_gui()


