#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 21, 2018 10:49:22 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.stocker import Change_Password_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Change_Password (root)
    Change_Password_support.init(root, top)
    root.mainloop()

w = None
def create_Change_Password(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Change_Password (w)
    Change_Password_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Change_Password():
    global w
    w.destroy()
    w = None


class Change_Password:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI Black} -size 18 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("555x355+650+236")
        top.title("Change_Password")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.03, relheight=0.94, relwidth=0.96)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(width=535)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.22, rely=0.09, height=46, width=312)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Change Password''')
        self.Label1.configure(width=312)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.09, rely=0.33, height=36, width=182)
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Old Password :''')
        self.Label2.configure(width=182)

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.07, rely=0.48, height=36, width=182)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font10)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''New Password :''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.02, rely=0.63, height=36, width=202)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font10)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Confirm Password :''')
        self.Label2_2.configure(width=202)

        self.OldPassword = Entry(self.Frame1)
        self.OldPassword.place(relx=0.43, rely=0.33,height=34, relwidth=0.47)
        self.OldPassword.configure(background="white")
        self.OldPassword.configure(disabledforeground="#a3a3a3")
        self.OldPassword.configure(font="TkFixedFont")
        self.OldPassword.configure(foreground="#000000")
        self.OldPassword.configure(insertbackground="black")
        self.OldPassword.configure(width=254)

        self.NewPassword = Entry(self.Frame1)
        self.NewPassword.place(relx=0.43, rely=0.48,height=34, relwidth=0.47)
        self.NewPassword.configure(background="white")
        self.NewPassword.configure(disabledforeground="#a3a3a3")
        self.NewPassword.configure(font="TkFixedFont")
        self.NewPassword.configure(foreground="#000000")
        self.NewPassword.configure(highlightbackground="#d9d9d9")
        self.NewPassword.configure(highlightcolor="black")
        self.NewPassword.configure(insertbackground="black")
        self.NewPassword.configure(selectbackground="#c4c4c4")
        self.NewPassword.configure(selectforeground="black")

        self.ConfirmPassword = Entry(self.Frame1)
        self.ConfirmPassword.place(relx=0.43, rely=0.63, height=34
                , relwidth=0.47)
        self.ConfirmPassword.configure(background="white")
        self.ConfirmPassword.configure(disabledforeground="#a3a3a3")
        self.ConfirmPassword.configure(font="TkFixedFont")
        self.ConfirmPassword.configure(foreground="#000000")
        self.ConfirmPassword.configure(highlightbackground="#d9d9d9")
        self.ConfirmPassword.configure(highlightcolor="black")
        self.ConfirmPassword.configure(insertbackground="black")
        self.ConfirmPassword.configure(selectbackground="#c4c4c4")
        self.ConfirmPassword.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.43, rely=0.78, height=33, width=96)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Change_Password_support.ChangePassword)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Change''')
        self.Button1.configure(width=96)






if __name__ == '__main__':
    vp_start_gui()



