#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 23, 2018 01:58:22 PM


import sys
from tkinter import messagebox
from main.com.nnk.stocker import Stocker_Home
from firebase import firebase as fb

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def Product_Delete():
    print('ProductDelete_support.Product_Delete')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None



def Product_Delete():
    pid = w.PDelete.get()
    from firebase import firebase as fb
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/product", None)
    result = fire.get("product", None)
    if pid == "":
        messagebox.showerror("Delete Id", "please enter product id")
    else:
        if pid in result:
            fire.delete("product", pid)
            messagebox.showerror("Delete product", "product is deleted")
        else:
            messagebox.showerror("Delete product", "please enter valid product id")
    return pid

def ProductDelete_Back():
    destroy_window()
    Stocker_Home.vp_start_gui()

if __name__ == '__main__':
    import ProductDelete
    ProductDelete.vp_start_gui()


