#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 20, 2018 02:04:12 PM

import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.stocker import ProductView_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Product_View (root)
    ProductView_support.init(root, top)
    root.mainloop()

w = None
def create_Product_View(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Product_View (w)
    ProductView_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Product_View():
    global w
    w.destroy()
    w = None


class Product_View:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI Black} -size 12 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("686x709+599+150")
        top.title("Product_View")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.01, relheight=0.08, relwidth=0.97)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=665)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.33, rely=0.18, height=26, width=92)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''PNO''')

        self.Label1_1 = Label(self.Frame1)
        self.Label1_1.place(relx=0.03, rely=0.18, height=26, width=92)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c4632b")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font9)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Name''')

        self.Label1_2 = Label(self.Frame1)
        self.Label1_2.place(relx=0.57, rely=0.18, height=26, width=92)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#c4632b")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font9)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Price''')

        self.Label1_3 = Label(self.Frame1)
        self.Label1_3.place(relx=0.8, rely=0.18, height=26, width=102)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#c4632b")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font9)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Quantity''')
        self.Label1_3.configure(width=102)

        self.ProductView = Frame(top)
        self.ProductView.place(relx=0.01, rely=0.08, relheight=0.91
                , relwidth=0.97)
        self.ProductView.configure(relief=GROOVE)
        self.ProductView.configure(borderwidth="10")
        self.ProductView.configure(relief=GROOVE)
        self.ProductView.configure(background="#c4632b")
        self.ProductView.configure(highlightbackground="#d9d9d9")
        self.ProductView.configure(highlightcolor="black")
        self.ProductView.configure(width=665)
        self.listofstockers()

    font5 = "-family {Segoe UI Black} -size 14 -weight bold -slant" \
             " italic -underline 0 -overstrike 0"

    def listofstockers(self):
        from firebase import firebase as fb
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/product", None)
        result = fire.get("product", None)
        if result == None:
            messagebox.showinfo("Details", "No Stocker Available")
        else:
            no_of_rows = len(result.keys())
            rows = []
            # for i in range(no_of_rows):
            counter =0
            for i in result:
                cols = []
                dt = result[i].values()
                val = []
                for x in dt:
                    val.append(x)
                for inner in range(1, 5):
                    l1 = Label(self.ProductView, width=13)
                    l1.configure(font=Product_View.font5)
                    l1.grid(row=counter, column=inner, sticky=NSEW)
                    l1.configure(text=val[inner - 1])
                    cols.append(l1)
                counter += 1



if __name__ == '__main__':
    vp_start_gui()



