#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 23, 2018 02:41:28 PM

import sys
from firebase import firebase as fb

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.stocker import ProductDelete_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Product_Delete (root)
    ProductDelete_support.init(root, top)
    root.mainloop()

w = None
def create_Product_Delete(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Product_Delete (w)
    ProductDelete_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Product_Delete():
    global w
    w.destroy()
    w = None


class Product_Delete:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI Black} -size 12 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("401x447+660+152")
        top.title("Product_Delete")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.ProductId_Delete = Frame(top)
        self.ProductId_Delete.place(relx=0.02, rely=0.02, relheight=0.95
                , relwidth=0.96)
        self.ProductId_Delete.configure(relief=GROOVE)
        self.ProductId_Delete.configure(borderwidth="10")
        self.ProductId_Delete.configure(relief=GROOVE)
        self.ProductId_Delete.configure(background="#c4632b")
        self.ProductId_Delete.configure(highlightbackground="#d9d9d9")
        self.ProductId_Delete.configure(highlightcolor="black")
        self.ProductId_Delete.configure(width=385)

        self.Label1 = Label(self.ProductId_Delete)
        self.Label1.place(relx=0.03, rely=0.09, height=26, width=292)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Enter product id to delete :''')

        self.PDelete = Entry(self.ProductId_Delete)
        self.PDelete.place(relx=0.08, rely=0.19,height=34, relwidth=0.79)
        self.PDelete.configure(background="white")
        self.PDelete.configure(disabledforeground="#a3a3a3")
        self.PDelete.configure(font="TkFixedFont")
        self.PDelete.configure(foreground="#000000")
        self.PDelete.configure(highlightbackground="#d9d9d9")
        self.PDelete.configure(highlightcolor="black")
        self.PDelete.configure(insertbackground="black")
        self.PDelete.configure(selectbackground="#c4c4c4")
        self.PDelete.configure(selectforeground="black")

        self.Button1 = Button(self.ProductId_Delete)
        self.Button1.place(relx=0.1, rely=0.85, height=33, width=96)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=ProductDelete_support.Product_Delete)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Delete''')

        self.Button1_1 = Button(self.ProductId_Delete)
        self.Button1_1.place(relx=0.65, rely=0.85, height=33, width=96)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(command=ProductDelete_support.ProductDelete_Back)
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font9)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Back''')

        self.Button1_2 = Button(self.ProductId_Delete)
        self.Button1_2.place(relx=0.31, rely=0.31, height=33, width=96)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#d9d9d9")
        self.Button1_2.configure(command=self.Display)
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font=font9)
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Show''')

        self.ProductShow = Frame(self.ProductId_Delete)
        self.ProductShow.place(relx=0.03, rely=0.42, relheight=0.39
                , relwidth=0.95)
        self.ProductShow.configure(relief=GROOVE)
        self.ProductShow.configure(borderwidth="2")
        self.ProductShow.configure(relief=GROOVE)
        self.ProductShow.configure(background="#c4632b")
        self.ProductShow.configure(width=365)

        self.Label1_3 = Label(self.ProductShow)
        self.Label1_3.place(relx=0.05, rely=0.19, height=26, width=72)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#c4632b")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font9)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Name :''')
        self.Label1_3.configure(width=72)

        self.ShowName = Label(self.ProductShow)
        self.ShowName.place(relx=0.27, rely=0.19, height=26, width=162)
        self.ShowName.configure(activebackground="#f9f9f9")
        self.ShowName.configure(activeforeground="black")
        self.ShowName.configure(background="#c4632b")
        self.ShowName.configure(disabledforeground="#a3a3a3")
        self.ShowName.configure(font=font9)
        self.ShowName.configure(foreground="#000000")
        self.ShowName.configure(highlightbackground="#d9d9d9")
        self.ShowName.configure(highlightcolor="black")
        self.ShowName.configure(text='''.................''')
        self.ShowName.configure(width=162)



        self.Label1_4 = Label(self.ProductShow)
        self.Label1_4.place(relx=0.05, rely=0.44, height=26, width=72)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#c4632b")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font=font9)
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Price :''')
        self.Label1_4.configure(width=72)

        self.Label1_4 = Label(self.ProductShow)
        self.Label1_4.place(relx=0.03, rely=0.68, height=26, width=112)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#c4632b")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font=font9)
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Quantity :''')
        self.Label1_4.configure(width=112)

        self.ShowPrice = Label(self.ProductShow)
        self.ShowPrice.place(relx=0.25, rely=0.44, height=26, width=162)
        self.ShowPrice.configure(activebackground="#f9f9f9")
        self.ShowPrice.configure(activeforeground="black")
        self.ShowPrice.configure(background="#c4632b")
        self.ShowPrice.configure(disabledforeground="#a3a3a3")
        self.ShowPrice.configure(font=font9)
        self.ShowPrice.configure(foreground="#000000")
        self.ShowPrice.configure(highlightbackground="#d9d9d9")
        self.ShowPrice.configure(highlightcolor="black")
        self.ShowPrice.configure(text='''.................''')

        self.ShowQuantuty = Label(self.ProductShow)
        self.ShowQuantuty.place(relx=0.33, rely=0.68, height=26, width=162)
        self.ShowQuantuty.configure(activebackground="#f9f9f9")
        self.ShowQuantuty.configure(activeforeground="black")
        self.ShowQuantuty. configure(background="#c4632b")
        self.ShowQuantuty.configure(disabledforeground="#a3a3a3")
        self.ShowQuantuty.configure(font=font9)
        self.ShowQuantuty.configure(foreground="#000000")
        self.ShowQuantuty.configure(highlightbackground="#d9d9d9")
        self.ShowQuantuty.configure(highlightcolor="black")
        self.ShowQuantuty.configure(text='''.................''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

    def Display(self, top=None):
        idno = self.PDelete.get()
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/product",None)
        result = fire.get("product", idno)
        self.ShowName.configure(text=result["pname"])
        self.ShowPrice.configure(text=result["price"])
        self.ShowQuantuty.configure(text=result["quantity"])


if __name__ == '__main__':
    vp_start_gui()



