#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 15, 2018 11:20:02 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.stocker import StockerHome_LogoutM_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = StockerHome_LogoutMessage (root)
    StockerHome_LogoutM_support.init(root, top)
    root.mainloop()

w = None
def create_StockerHome_LogoutMessage(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = StockerHome_LogoutMessage (w)
    StockerHome_LogoutM_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_StockerHome_LogoutMessage():
    global w
    w.destroy()
    w = None


class StockerHome_LogoutMessage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 12 -weight bold -slant "  \
            "italic -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 10 -weight bold -slant "  \
            "italic -underline 0 -overstrike 0"

        top.geometry("274x135+732+301")
        top.title("StockerHome_LogoutMessage")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(width=275)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.15, rely=0.07, height=36, width=192)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Do you really want''')
        self.Label1.configure(width=192)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.25, rely=0.3, height=26, width=122)
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''to Logout?''')
        self.Label2.configure(width=122)

        self.Button2_2 = Button(self.Frame1)
        self.Button2_2.place(relx=0.22, rely=0.59, height=28, width=61)
        self.Button2_2.configure(activebackground="#d9d9d9")
        self.Button2_2.configure(activeforeground="#000000")
        self.Button2_2.configure(background="#d9d9d9")
        self.Button2_2.configure(command=StockerHome_LogoutM_support.StockerHome_LogoutYes)
        self.Button2_2.configure(disabledforeground="#a3a3a3")
        self.Button2_2.configure(font=font11)
        self.Button2_2.configure(foreground="#000000")
        self.Button2_2.configure(highlightbackground="#d9d9d9")
        self.Button2_2.configure(highlightcolor="black")
        self.Button2_2.configure(pady="0")
        self.Button2_2.configure(text='''Yes''')
        self.Button2_2.configure(width=61)

        self.Button2_3 = Button(self.Frame1)
        self.Button2_3.place(relx=0.58, rely=0.59, height=28, width=61)
        self.Button2_3.configure(activebackground="#d9d9d9")
        self.Button2_3.configure(activeforeground="#000000")
        self.Button2_3.configure(background="#d9d9d9")
        self.Button2_3.configure(command=StockerHome_LogoutM_support.StockerHome_LogoutNo)
        self.Button2_3.configure(disabledforeground="#a3a3a3")
        self.Button2_3.configure(font=font11)
        self.Button2_3.configure(foreground="#000000")
        self.Button2_3.configure(highlightbackground="#d9d9d9")
        self.Button2_3.configure(highlightcolor="black")
        self.Button2_3.configure(pady="0")
        self.Button2_3.configure(text='''No''')






if __name__ == '__main__':
    vp_start_gui()



