#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 15, 2018 11:18:51 PM


import sys
from main.com.nnk.stocker import stocker
from  main.com.nnk.stocker import Stocker_Home
from  main.com.nnk.stocker import Stocker_Home_support

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def StockerHome_LogoutNo():
    print('StockerHome_Logout_support.StockerHome_LogoutNo')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def StockerHome_LogoutYes():
    destroy_window()
    Stocker_Home_support.destroy_window()
    stocker.vp_start_gui()


def StockerHome_LogoutNo():

    destroy_window()


if __name__ == '__main__':
    import StockerHome_LogoutM
    StockerHome_LogoutM.vp_start_gui()


