#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 10:21:06 PM


import sys
from main.com.nnk.stocker import Stocker_Home
from tkinter import messagebox
from firebase import firebase as fb
import re
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def validateStockerLogin():
    print('stocker_support.validateStockerLogin')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def validateStockerLogin():
    name = w.stockerusername.get()
    from main.com.nnk.stocker import Change_Password_support as c
    c.variable(name)
    password = w.stockerpassword.get()
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/stocker", None)
    s = fire.get("stocker", None)
    if name == "":
        messagebox.showerror("Stocker_Login", "Enter the username")
    elif password == "":
        messagebox.showerror("Stocker_Login", "Enter the password")
    else:
        if (name in s) and (s[name]["pass"] == password):
            Stocker_Home.vp_start_gui()
        else:
            messagebox.showerror("Stocker_Login", "Invalid username or password")
    return name

if __name__ == '__main__':
    import stocker
    stocker.vp_start_gui()


