#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 27, 2018 01:12:41 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import _support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Send_Order (root)
    _support.init(root, top)
    root.mainloop()

w = None
def create_Send_Order(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Send_Order (w)
    _support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Send_Order():
    global w
    w.destroy()
    w = None


class Send_Order:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 13 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI Black} -size 16 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("575x743+672+144")
        top.title("Send_Order")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=0.0, relwidth=0.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=555)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.0, rely=0.0, height=1, width=1)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Send Order''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.0, rely=0.0, height=1, width=1)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Order NO :''')

        self.Order_No = Entry(self.Frame1)
        self.Order_No.place(relx=0.0, rely=0.0,height=1, relwidth=1.0)
        self.Order_No.configure(background="white")
        self.Order_No.configure(disabledforeground="#a3a3a3")
        self.Order_No.configure(font="TkFixedFont")
        self.Order_No.configure(foreground="#000000")
        self.Order_No.configure(highlightbackground="#d9d9d9")
        self.Order_No.configure(highlightcolor="black")
        self.Order_No.configure(insertbackground="black")
        self.Order_No.configure(selectbackground="#c4c4c4")
        self.Order_No.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.0, rely=0.0, height=1, width=1)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=_support.SOrder_Show)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Show''')

        self.Send_Show = Frame(self.Frame1)
        self.Send_Show.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Send_Show.configure(relief=GROOVE)
        self.Send_Show.configure(borderwidth="2")
        self.Send_Show.configure(relief=GROOVE)
        self.Send_Show.configure(background="#c4632b")
        self.Send_Show.configure(highlightbackground="#d9d9d9")
        self.Send_Show.configure(highlightcolor="black")
        self.Send_Show.configure(width=515)

        self.Label2_1 = Label(self.Send_Show)
        self.Label2_1.place(relx=0.0, rely=0.0, height=1, width=1)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font10)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name :''')

        self.Label2_2 = Label(self.Send_Show)
        self.Label2_2.place(relx=0.0, rely=0.0, height=1, width=1)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font10)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Pno :''')

        self.fra38_fra43_lab48 = Label(self.Send_Show)
        self.fra38_fra43_lab48.place(relx=0.0, rely=0.0, height=1, width=1)
        self.fra38_fra43_lab48.configure(activebackground="#f9f9f9")
        self.fra38_fra43_lab48.configure(activeforeground="black")
        self.fra38_fra43_lab48.configure(background="#c4632b")
        self.fra38_fra43_lab48.configure(disabledforeground="#a3a3a3")
        self.fra38_fra43_lab48.configure(font=font10)
        self.fra38_fra43_lab48.configure(foreground="#000000")
        self.fra38_fra43_lab48.configure(highlightbackground="#d9d9d9")
        self.fra38_fra43_lab48.configure(highlightcolor="black")
        self.fra38_fra43_lab48.configure(text='''Price :''')






if __name__ == '__main__':
    vp_start_gui()



