#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 10:34:16 AM


import sys
from firebase import firebase as fb
from tkinter import messagebox
from main.com.nnk.dispatcher import Dispatcher_Home


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def DispatcherHome_CBack():
    print('DipatcherChangePassword_support.DispatcherHome_CBack')
    sys.stdout.flush()

def DispatcherHome_CSave():
    print('DipatcherChangePassword_support.DispatcherHome_CSave')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def variable(u):
    global d
    d = u

def DispatcherHome_CSave():
    old = w.DOldPassword.get()
    new = w.DNewPassword.get()
    confirm = w.DConfirmPassword.get()
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher", None)
    result = fire.get("dispatcher", d)
    if old == "":
        messagebox.showerror("Change Password", "Enter the old password")
    elif new == "":
        messagebox.showerror("Change Password", "Enter the new password")
    elif confirm == "":
        messagebox.showerror("Change Password", "Enter the confirm password")
    else:
        if result["password"] == old and new == confirm:
            fire.put("dispatcher", d, {"name": result["name"], "cno": result["cno"], "password": new})
            messagebox.showerror("Change Password", "Password is changed")
        else:
            messagebox.showerror("Change Password", "Invalid old password")

def DispatcherHome_CBack():
    destroy_window()
    Dispatcher_Home.vp_start_gui()

if __name__ == '__main__':
    import DipatcherChangePassword
    DipatcherChangePassword.vp_start_gui()


