#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 10:34:24 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.dispatcher import DipatcherChangePassword_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = DChangePassword (root)
    DipatcherChangePassword_support.init(root, top)
    root.mainloop()

w = None
def create_DChangePassword(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = DChangePassword (w)
    DipatcherChangePassword_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_DChangePassword():
    global w
    w.destroy()
    w = None


class DChangePassword:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI Black} -size 11 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("474x233+699+276")
        top.title("DChangePassword")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.04, relheight=0.92, relwidth=0.96)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=455)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.04, rely=0.14, height=26, width=152)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Old Password :''')

        self.Label1_1 = Label(self.Frame1)
        self.Label1_1.place(relx=0.04, rely=0.33, height=26, width=152)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c4632b")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font9)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''New Password :''')

        self.Label1_2 = Label(self.Frame1)
        self.Label1_2.place(relx=0.02, rely=0.51, height=26, width=192)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#c4632b")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font9)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Confirm Password :''')

        self.DOldPassword = Entry(self.Frame1)
        self.DOldPassword.place(relx=0.37, rely=0.14,height=24, relwidth=0.4)
        self.DOldPassword.configure(background="white")
        self.DOldPassword.configure(disabledforeground="#a3a3a3")
        self.DOldPassword.configure(font="TkFixedFont")
        self.DOldPassword.configure(foreground="#000000")
        self.DOldPassword.configure(highlightbackground="#d9d9d9")
        self.DOldPassword.configure(highlightcolor="black")
        self.DOldPassword.configure(insertbackground="black")
        self.DOldPassword.configure(selectbackground="#c4c4c4")
        self.DOldPassword.configure(selectforeground="black")

        self.DNewPassword = Entry(self.Frame1)
        self.DNewPassword.place(relx=0.4, rely=0.33,height=24, relwidth=0.4)
        self.DNewPassword.configure(background="white")
        self.DNewPassword.configure(disabledforeground="#a3a3a3")
        self.DNewPassword.configure(font="TkFixedFont")
        self.DNewPassword.configure(foreground="#000000")
        self.DNewPassword.configure(highlightbackground="#d9d9d9")
        self.DNewPassword.configure(highlightcolor="black")
        self.DNewPassword.configure(insertbackground="black")
        self.DNewPassword.configure(selectbackground="#c4c4c4")
        self.DNewPassword.configure(selectforeground="black")

        self.DConfirmPassword = Entry(self.Frame1)
        self.DConfirmPassword.place(relx=0.44, rely=0.51, height=24
                , relwidth=0.4)
        self.DConfirmPassword.configure(background="white")
        self.DConfirmPassword.configure(disabledforeground="#a3a3a3")
        self.DConfirmPassword.configure(font="TkFixedFont")
        self.DConfirmPassword.configure(foreground="#000000")
        self.DConfirmPassword.configure(highlightbackground="#d9d9d9")
        self.DConfirmPassword.configure(highlightcolor="black")
        self.DConfirmPassword.configure(insertbackground="black")
        self.DConfirmPassword.configure(selectbackground="#c4c4c4")
        self.DConfirmPassword.configure(selectforeground="black")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.24, rely=0.74, height=33, width=76)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=DipatcherChangePassword_support.DispatcherHome_CBack)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Back''')

        self.Button1_5 = Button(self.Frame1)
        self.Button1_5.place(relx=0.57, rely=0.74, height=33, width=76)
        self.Button1_5.configure(activebackground="#d9d9d9")
        self.Button1_5.configure(activeforeground="#000000")
        self.Button1_5.configure(background="#d9d9d9")
        self.Button1_5.configure(command=DipatcherChangePassword_support.DispatcherHome_CSave)
        self.Button1_5.configure(disabledforeground="#a3a3a3")
        self.Button1_5.configure(font=font9)
        self.Button1_5.configure(foreground="#000000")
        self.Button1_5.configure(highlightbackground="#d9d9d9")
        self.Button1_5.configure(highlightcolor="black")
        self.Button1_5.configure(pady="0")
        self.Button1_5.configure(text='''Save''')






if __name__ == '__main__':
    vp_start_gui()



