#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 17, 2018 10:40:05 AM


import sys
from main.com.nnk.dispatcher import dispatcher
from main.com.nnk.dispatcher import Dispatcher_Home_support
from main import merchant

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def DispatcherHome_LogoutNo():
    print('DispatcherHome_LogoutM_support.DispatcherHome_LogoutNo')
    sys.stdout.flush()

def DispatcherHome_LogoutYes():
    print('DispatcherHome_LogoutM_support.DispatcherHome_LogoutYes')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def DispatcherHome_LogoutYes():
    destroy_window()
    Dispatcher_Home_support.destroy_window()
    dispatcher.vp_start_gui()

def DispatcherHome_LogoutNo():
    destroy_window()
    merchant.vp_start_gui()

if __name__ == '__main__':
    import DispatcherHome_LogoutM
    DispatcherHome_LogoutM.vp_start_gui()


