#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 26, 2018 08:28:13 PM

import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.dispatcher import DispatcherViewOrder_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = View_Order (root)
    DispatcherViewOrder_support.init(root, top)
    root.mainloop()

w = None
def create_View_Order(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = View_Order (w)
    DispatcherViewOrder_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_View_Order():
    global w
    w.destroy()
    w = None


class View_Order:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        top.geometry("1117x733+420+149")
        top.title("View Order")
        top.configure(background="#d9d9d9")



        self.View_Orders = Frame(top)
        self.View_Orders.place(relx=0.01, rely=0.11, relheight=0.88
                , relwidth=0.98)
        self.View_Orders.configure(relief=GROOVE)
        self.View_Orders.configure(borderwidth="10")
        self.View_Orders.configure(relief=GROOVE)
        self.View_Orders.configure(background="#c4632b")
        self.View_Orders.configure(width=1080)
        self.listofstockers()

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.01, rely=0.01, relheight=0.1, relwidth=0.98)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="10")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#c4632b")
        self.Frame2.configure(width=1040)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.02, rely=0.4, height=26, width=122)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Order No.''')
        self.Label1.configure(width=122)

        self.Label1_1 = Label(self.Frame2)
        self.Label1_1.place(relx=0.18, rely=0.4, height=26, width=122)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c4632b")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font10)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Name''')

        self.Label1_2 = Label(self.Frame2)
        self.Label1_2.place(relx=0.36, rely=0.4, height=26, width=122)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#c4632b")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font10)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''PNO''')

        self.Label1_3 = Label(self.Frame2)
        self.Label1_3.place(relx=0.53, rely=0.4, height=26, width=122)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#c4632b")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font10)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Price''')

        self.Label1_4 = Label(self.Frame2)
        self.Label1_4.place(relx=0.69, rely=0.4, height=26, width=122)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#c4632b")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font=font10)
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Quantity''')

        self.Label1_5 = Label(self.Frame2)
        self.Label1_5.place(relx=0.86, rely=0.4, height=26, width=122)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#c4632b")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font=font10)
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''Total''')

    font10 = "-family {Segoe UI Black} -size 12 -weight bold " \
             "-slant italic -underline 0 -overstrike 0"

    def listofstockers(self):
        from firebase import firebase as fb
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher/orderno", None)
        result = fire.get("orderno", None)
        if result == None:
            messagebox.showinfo("Details", "No Order Available")
        else:
            rows = []
            # for i in range(no_of_rows):
            counter = 0
            for i in result:
                cols = []
                l = Label(self.View_Orders, w, width=16)
                l.configure(font=View_Order.font10)
                l.configure(background="#c4632b")
                l.configure(borderwidth="10")
                l.grid(row=counter, column=0, sticky=NSEW)
                l.configure(text=i)
                dt = result[i].values()
                val = []
                for x in dt:
                    val.append(x)
                for inner in range(1, 6):
                    l1 = Label(self.View_Orders, width=15)
                    l1.configure(font=View_Order.font10)
                    l1.grid(row=counter, column=inner, sticky=NSEW)
                    l1.configure(background="#c4632b")
                    l1.configure(borderwidth="10")
                    l1.configure(text=val[inner - 1])
                    cols.append(l1)
                counter += 1
            rows.append(l)






if __name__ == '__main__':
    vp_start_gui()



