#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 17, 2018 10:27:23 AM


import sys
from main.com.nnk.dispatcher import DispatcherHome_LogoutM
from main.com.nnk.dispatcher import DipatcherChangePassword
from main.com.nnk.dispatcher import DispatcherViewOrder
from main.com.nnk.admin import SalesView
from main.com.nnk.dispatcher import SendOrder

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def DispatcherHome_Logout():
    print('Dispatcher_Home_support.DispatcherHome_Logout')
    sys.stdout.flush()

def DispatcherHome_SentOrder():
    print('Dispatcher_Home_support.DispatcherHome_SentOrder')
    sys.stdout.flush()

def DispatcherHome_ViewOrder():
    print('Dispatcher_Home_support.DispatcherHome_ViewOrder')
    sys.stdout.flush()

def DispatcherHome_ViewStock():
    print('Dispatcher_Home_support.DispatcherHome_ViewStock')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def DispatcherHome_ChangePassword():
    destroy_window()
    DipatcherChangePassword.vp_start_gui()

def DispatcherHome_ViewOrder():
    DispatcherViewOrder.vp_start_gui()

def DispatcherHome_SendOrder():
    destroy_window()
    SendOrder.vp_start_gui()

def DispatcherHome_ViewSendOrder():
    SalesView.vp_start_gui()

def DispatcherHome_Logout():
    DispatcherHome_LogoutM.vp_start_gui()

if __name__ == '__main__':
    import Dispatcher_Home
    Dispatcher_Home.vp_start_gui()


