#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 10:48:43 PM


import sys
from tkinter import messagebox
from firebase import firebase as fb
from main.com.nnk.dispatcher import Dispatcher_Home

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def validateDispatcherLogin():
    print('dispatcher_support.validateDispatcherLogin')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def validateDispatcherLogin():
    name = w.dispatcherusername.get()
    from main.com.nnk.dispatcher import DipatcherChangePassword_support as c
    c.variable(name)
    password = w.dispatcherpassword.get()
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher", None)
    s = fire.get("dispatcher", None)
    if name == "":
        messagebox.showerror("Dispatcher_Login", "Enter the username")
    elif password == "":
        messagebox.showerror("Dispatcher_Login", "Enter the password")
    else:
        if (name in s) and (s[name]["password"] == password):
            Dispatcher_Home.vp_start_gui()
        else:
            messagebox.showerror("Dispatcher_Login", "Invalid username or password")


if __name__ == '__main__':
    import dispatcher
    dispatcher.vp_start_gui()



