#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 26, 2018 11:33:37 PM

import sys
from firebase import firebase as fb
from tkinter import messagebox
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.dispatcher import SendOrder_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Send_Order (root)
    SendOrder_support.init(root, top)
    root.mainloop()

w = None
def create_Send_Order(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Send_Order (w)
    SendOrder_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Send_Order():
    global w
    w.destroy()
    w = None


class Send_Order:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 16 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI Black} -size 13 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font17 = "-family {Segoe UI Black} -size 19 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        top.geometry("489x647+650+150")
        top.title("Send_Order")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.02, relheight=0.97, relwidth=0.95)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(width=555)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.30, rely=0.03, height=36, width=212)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Send Order''')
        self.Label1.configure(width=212)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.02, rely=0.12, height=36, width=142)
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Order NO :''')
        self.Label2.configure(width=142)

        self.Order_No = Entry(self.Frame1)
        self.Order_No.place(relx=0.28, rely=0.12,height=34, relwidth=0.44)
        self.Order_No.configure(background="white")
        self.Order_No.configure(disabledforeground="#a3a3a3")
        self.Order_No.configure(font="TkFixedFont")
        self.Order_No.configure(foreground="#000000")
        self.Order_No.configure(insertbackground="black")
        self.Order_No.configure(width=244)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.43, rely=0.21, height=43, width=76)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.Show)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Show''')
        self.Button1.configure(width=76)

        self.Send_Show = Frame(self.Frame1)
        self.Send_Show.place(relx=0.04, rely=0.32, relheight=0.55, relwidth=0.93)
        self.Send_Show.configure(relief=GROOVE)
        self.Send_Show.configure(borderwidth="2")
        self.Send_Show.configure(relief=GROOVE)
        self.Send_Show.configure(background="#c4632b")
        self.Send_Show.configure(width=515)


        self.Label2_2 = Label(self.Send_Show)
        self.Label2_2.place(relx=0.12, rely=0.28, height=36, width=112)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Pno :''')

        self.Label2_2 = Label(self.Send_Show)
        self.Label2_2.place(relx=0.1, rely=0.45, height=36, width=112)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Price :''')

        self.Label2_2 = Label(self.Send_Show)
        self.Label2_2.place(relx=0.06, rely=0.62, height=36, width=112)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Quantity :''')

        self.Label2_2 = Label(self.Send_Show)
        self.Label2_2.place(relx=0.1, rely=0.78, height=36, width=112)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Total :''')

        self.Label2_2 = Label(self.Send_Show)
        self.Label2_2.place(relx=0.0, rely=0.1, height=36, width=162)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Prod. Name :''')
        self.Label2_2.configure(width=162)


        self.SPName = Label(self.Send_Show)
        self.SPName.place(relx=0.34, rely=0.1, height=36, width=117)
        self.SPName.configure(activebackground="#f9f9f9")
        self.SPName.configure(activeforeground="black")
        self.SPName.configure(background="#c4632b")
        self.SPName.configure(disabledforeground="#a3a3a3")
        self.SPName.configure(font=font11)
        self.SPName.configure(foreground="#000000")
        self.SPName.configure(highlightbackground="#d9d9d9")
        self.SPName.configure(highlightcolor="black")
        self.SPName.configure(text='''.................''')

        self.SPNO = Label(self.Send_Show)
        self.SPNO.place(relx=0.31, rely=0.28, height=36, width=112)
        self.SPNO.configure(activebackground="#f9f9f9")
        self.SPNO.configure(activeforeground="black")
        self.SPNO.configure(background="#c4632b")
        self.SPNO.configure(disabledforeground="#a3a3a3")
        self.SPNO.configure(font=font11)
        self.SPNO.configure(foreground="#000000")
        self.SPNO.configure(highlightbackground="#d9d9d9")
        self.SPNO.configure(highlightcolor="black")
        self.SPNO.configure(text='''.............''')

        self.SPPrice = Label(self.Send_Show)
        self.SPPrice.place(relx=0.31, rely=0.45, height=36, width=112)
        self.SPPrice.configure(activebackground="#f9f9f9")
        self.SPPrice.configure(activeforeground="black")
        self.SPPrice.configure(background="#c4632b")
        self.SPPrice.configure(disabledforeground="#a3a3a3")
        self.SPPrice.configure(font=font11)
        self.SPPrice.configure(foreground="#000000")
        self.SPPrice.configure(highlightbackground="#d9d9d9")
        self.SPPrice.configure(highlightcolor="black")
        self.SPPrice.configure(text='''.............''')

        self.SPquantity = Label(self.Send_Show)
        self.SPquantity.place(relx=0.31, rely=0.62, height=36, width=112)
        self.SPquantity.configure(activebackground="#f9f9f9")
        self.SPquantity.configure(activeforeground="black")
        self.SPquantity.configure(background="#c4632b")
        self.SPquantity.configure(disabledforeground="#a3a3a3")
        self.SPquantity.configure(font=font11)
        self.SPquantity.configure(foreground="#000000")
        self.SPquantity.configure(highlightbackground="#d9d9d9")
        self.SPquantity.configure(highlightcolor="black")
        self.SPquantity.configure(text='''.............''')

        self.SPTotal = Label(self.Send_Show)
        self.SPTotal.place(relx=0.31, rely=0.78, height=36, width=112)
        self.SPTotal.configure(activebackground="#f9f9f9")
        self.SPTotal.configure(activeforeground="black")
        self.SPTotal.configure(background="#c4632b")
        self.SPTotal.configure(disabledforeground="#a3a3a3")
        self.SPTotal.configure(font=font11)
        self.SPTotal.configure(foreground="#000000")
        self.SPTotal.configure(highlightbackground="#d9d9d9")
        self.SPTotal.configure(highlightcolor="black")
        self.SPTotal.configure(text='''.............''')

        self.Button1_4 = Button(self.Frame1)
        self.Button1_4.place(relx=0.45, rely=0.90, height=43, width=76)
        self.Button1_4.configure(activebackground="#d9d9d9")
        self.Button1_4.configure(activeforeground="#000000")
        self.Button1_4.configure(background="#d9d9d9")
        self.Button1_4.configure(command=SendOrder_support.SOrder_Send)
        self.Button1_4.configure(disabledforeground="#a3a3a3")
        self.Button1_4.configure(font=font12)
        self.Button1_4.configure(foreground="#000000")
        self.Button1_4.configure(highlightbackground="#d9d9d9")
        self.Button1_4.configure(highlightcolor="black")
        self.Button1_4.configure(pady="0")
        self.Button1_4.configure(text='''Send''')

    def Show(self):
        ono = self.Order_No.get()
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher/orderno", None)
        result = fire.get("orderno", None)
        if result is None:
            messagebox.showinfo("Show Order", "No order is present ")
        elif ono == "":
            messagebox.showerror("Show Order", "Product number is empty")
        else:
            if ono in result:
                self.SPName.configure(text=result[ono]["name"])
                self.SPNO.configure(text=result[ono]["pno"])
                self.SPPrice.configure(text=result[ono]["price"])
                self.SPquantity.configure(text=result[ono]["quantity"])
                self.SPTotal.configure(text=result[ono]["total"])
            else:
                messagebox.showerror("Show Order", "Order no is wrong")


if __name__ == '__main__':
    vp_start_gui()



