#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 26, 2018 11:33:17 PM


import sys
from firebase import firebase as fb
from tkinter import messagebox
from main.com.nnk.dispatcher import Dispatcher_Home

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def SOrder_Send():
    print('SendOrder_support.SOrder_Send')
    sys.stdout.flush()

def SOrder_Show():
    print('SendOrder_support.SOrder_Show')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def Sales_Id():
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/sales", None)
    result = fire.get("sales", None)
    if result == None:
        pass
        return "1001"
    else:
        for x in result:
            pass
        idno = int(x)
        idno += 1
        return str(idno)


def SOrder_Send():
    ono = w.Order_No.get()
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher/orderno", None)
    result = fire.get("orderno", None)
    if result is None:
        messagebox.showinfo("Send Order", "No order is present")
    elif ono == "":
        messagebox.showerror("Place Order", "Product number is empty")
    else:
        if ono in result:
            n = result[ono]["name"]
            q = result[ono]["quantity"]
            t = result[ono]["price"]
            s = result[ono]["pno"]
            total = result[ono]["total"]
            id = Sales_Id()
            fire2 = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/sales", None)
            fire2.put("sales", id, {"name": n, "price": t, "quantity": q, "total": total, "pno": s})
            fire3 = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher/orderno", None)
            fire3.delete("orderno", ono)
            if messagebox.askyesno("Send Order", "Order is send ,Do you want to continue") == True:
                pass
            else:
                destroy_window()
                Dispatcher_Home.vp_start_gui()
        else:
            messagebox.showerror("Send Order", "Order number is wrong")


if __name__ == '__main__':
    import SendOrder
    SendOrder.vp_start_gui()


