#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 12:42:09 PM


import sys
from main.customer import CustomerChangePassword
from main.customer import CustomerLogin
from main.customer import Place_Order
from main.customer import ViewOrdered
from main.com.nnk.stocker import ProductView
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def Customer_ChangePassword():
    print('Customer_Home_support.Customer_ChangePassword')
    sys.stdout.flush()

def Customer_Logout():
    print('Customer_Home_support.Customer_Logout')
    sys.stdout.flush()

def Customer_PlaceOrder():
    print('Customer_Home_support.Customer_PlaceOrder')
    sys.stdout.flush()

def Customer_ViewOrdered():
    print('Customer_Home_support.Customer_ViewOrdered')
    sys.stdout.flush()

def Customer_ViewProduct():
    print('Customer_Home_support.Customer_ViewProduct')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def Customer_ViewProduct():
    ProductView.vp_start_gui()


def Customer_PlaceOrder():
    destroy_window()
    Place_Order.vp_start_gui()

def Customer_ViewOrdered():
    ViewOrdered.vp_start_gui()

def Customer_ChangePassword():
    destroy_window()
    CustomerChangePassword.vp_start_gui()

def Customer_Logout():
    if messagebox.askyesno("Logout","Do you really want to logout") == True:
        destroy_window()
        CustomerLogin.vp_start_gui()
    else:
        pass

if __name__ == '__main__':
    import Customer_Home
    Customer_Home.vp_start_gui()


