#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 11:46:47 AM


import sys
from main.customer import CustomerLogin

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def CustomerHome():
    print('customer_support.CustomerHome')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def CustomerHome():
    destroy_window()
    CustomerLogin.vp_start_gui()

if __name__ == '__main__':
    import customer
    customer.vp_start_gui()


