#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 12:21:57 PM


import sys
from main.customer import CustomerLogin
from tkinter import messagebox
from firebase import firebase as fb
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def Register_Save():
    print('Customer_Register_support.Register_Save')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def CustomerRegistration_Id():
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/customer/login", None)
    result = fire.get("login", None)
    for x in result.keys():
        pass
    idno = int(x)
    idno += 1
    return str(idno)

def Register_Save():
    idno = CustomerRegistration_Id()
    name = w.RegisterName.get()
    cno = w.RegisterCno.get()
    password = w.RegisterPassword.get()
    address = w.RegisterAddress.get()
    name1 = re.search(r"\w+[a-zA-Z]", name)
    password1 = re.search(r"\w+[a-zA-Z0-9]", password)
    cno1 = re.search(r"\w+[0-9]", cno)
    address1 = re.search(r"\w+[a-zA-Z0-9]", address)
    if name == "":
        messagebox.showerror("Customer Registration", "Please enter the name")
    elif password == "":
        messagebox.showerror("Customer Registration", "Please enter the password")
    elif cno == "":
        messagebox.showerror("Customer Registration", "Please enter the contact no.")
    elif address == "":
        messagebox.showerror("Customer Registration", "Please enter the address")
    elif name1 == None:
        messagebox.showerror("Customer Registration", "Please enter proper name")
    elif password1 == None:
        messagebox.showerror("Customer Registration", "Please enter proper password")
    elif cno1 == None:
        messagebox.showerror("Customer Registration", "Please enter proper contact no")
    elif address1 == None:
        messagebox.showerror("Customer Registration", "Please enter proper address")
    else:
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/customer/login", None)
        fire.put("login", idno, {"name": name, "cno": int(cno), "pass": password, "address": address})
        messagebox.showinfo("Customer Registration", "Information is saved")
        destroy_window()
        CustomerLogin.vp_start_gui()


if __name__ == '__main__':
    import Customer_Register
    Customer_Register.vp_start_gui()


