#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 01:00:30 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.customer import CustomerChangePassword_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = CustomerChangePassword (root)
    CustomerChangePassword_support.init(root, top)
    root.mainloop()

w = None
def create_CustomerChangePassword(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = CustomerChangePassword (w)
    CustomerChangePassword_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_CustomerChangePassword():
    global w
    w.destroy()
    w = None


class CustomerChangePassword:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI Black} -size 12 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("517x273+707+223")
        top.title("CustomerChangePassword")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.04, relheight=0.93, relwidth=0.96)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(width=495)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.02, rely=0.2, height=26, width=182)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Old Password :''')
        self.Label1.configure(width=182)

        self.Label1_1 = Label(self.Frame1)
        self.Label1_1.place(relx=0.02, rely=0.39, height=26, width=182)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c4632b")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font9)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''New Password :''')

        self.Label1_2 = Label(self.Frame1)
        self.Label1_2.place(relx=0.04, rely=0.59, height=26, width=192)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#c4632b")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font9)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Confirm Password :''')
        self.Label1_2.configure(width=192)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.44, rely=0.78, height=33, width=66)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=CustomerChangePassword_support.CustomerChangeP_Save)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')
        self.Button1.configure(width=66)

        self.CustomerCP_Old = Entry(self.Frame1)
        self.CustomerCP_Old.place(relx=0.38, rely=0.2,height=34, relwidth=0.47)
        self.CustomerCP_Old.configure(background="white")
        self.CustomerCP_Old.configure(disabledforeground="#a3a3a3")
        self.CustomerCP_Old.configure(font="TkFixedFont")
        self.CustomerCP_Old.configure(foreground="#000000")
        self.CustomerCP_Old.configure(insertbackground="black")
        self.CustomerCP_Old.configure(width=234)

        self.CustomerCP_New = Entry(self.Frame1)
        self.CustomerCP_New.place(relx=0.38, rely=0.39, height=34, relwidth=0.47)

        self.CustomerCP_New.configure(background="white")
        self.CustomerCP_New.configure(disabledforeground="#a3a3a3")
        self.CustomerCP_New.configure(font="TkFixedFont")
        self.CustomerCP_New.configure(foreground="#000000")
        self.CustomerCP_New.configure(highlightbackground="#d9d9d9")
        self.CustomerCP_New.configure(highlightcolor="black")
        self.CustomerCP_New.configure(insertbackground="black")
        self.CustomerCP_New.configure(selectbackground="#c4c4c4")
        self.CustomerCP_New.configure(selectforeground="black")

        self.CustomerCP_Confirm = Entry(self.Frame1)
        self.CustomerCP_Confirm.place(relx=0.44, rely=0.59, height=34
                , relwidth=0.47)
        self.CustomerCP_Confirm.configure(background="white")
        self.CustomerCP_Confirm.configure(disabledforeground="#a3a3a3")
        self.CustomerCP_Confirm.configure(font="TkFixedFont")
        self.CustomerCP_Confirm.configure(foreground="#000000")
        self.CustomerCP_Confirm.configure(highlightbackground="#d9d9d9")
        self.CustomerCP_Confirm.configure(highlightcolor="black")
        self.CustomerCP_Confirm.configure(insertbackground="black")
        self.CustomerCP_Confirm.configure(selectbackground="#c4c4c4")
        self.CustomerCP_Confirm.configure(selectforeground="black")






if __name__ == '__main__':
    vp_start_gui()



