#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 24, 2018 12:22:17 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.customer import Customer_Register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Customer_Registration (root)
    Customer_Register_support.init(root, top)
    root.mainloop()

w = None
def create_Customer_Registration(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Customer_Registration (w)
    Customer_Register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Customer_Registration():
    global w
    w.destroy()
    w = None


class Customer_Registration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Segoe UI Black} -size 15 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"

        top.geometry("474x422+758+163")
        top.title("Customer_Registration")
        top.configure(background="#d9d9d9")



        self.Frame_1 = Frame(top)
        self.Frame_1.place(relx=0.02, rely=0.02, relheight=0.96, relwidth=0.96)
        self.Frame_1.configure(relief=GROOVE)
        self.Frame_1.configure(borderwidth="10")
        self.Frame_1.configure(relief=GROOVE)
        self.Frame_1.configure(background="#c4632b")
        self.Frame_1.configure(width=455)

        self.Label1 = Label(self.Frame_1)
        self.Label1.place(relx=0.22, rely=0.07, height=36, width=262)
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Register''')
        self.Label1.configure(width=262)

        self.Label2 = Label(self.Frame_1)
        self.Label2.place(relx=0.09, rely=0.25, height=26, width=132)
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Name :''')
        self.Label2.configure(width=132)

        self.Label2_1 = Label(self.Frame_1)
        self.Label2_1.place(relx=0.02, rely=0.4, height=26, width=132)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font12)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Contact No :''')

        self.Label2_2 = Label(self.Frame_1)
        self.Label2_2.place(relx=0.04, rely=0.54, height=26, width=132)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font12)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Address :''')

        self.Label2_3 = Label(self.Frame_1)
        self.Label2_3.place(relx=0.02, rely=0.69, height=26, width=132)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#c4632b")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font12)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Password :''')

        self.RegisterName = Entry(self.Frame_1)
        self.RegisterName.place(relx=0.33, rely=0.25,height=34, relwidth=0.54)
        self.RegisterName.configure(background="white")
        self.RegisterName.configure(disabledforeground="#a3a3a3")
        self.RegisterName.configure(font="TkFixedFont")
        self.RegisterName.configure(foreground="#000000")
        self.RegisterName.configure(insertbackground="black")
        self.RegisterName.configure(width=244)

        self.RegisterCno = Entry(self.Frame_1)
        self.RegisterCno.place(relx=0.33, rely=0.4,height=34, relwidth=0.54)
        self.RegisterCno.configure(background="white")
        self.RegisterCno.configure(disabledforeground="#a3a3a3")
        self.RegisterCno.configure(font="TkFixedFont")
        self.RegisterCno.configure(foreground="#000000")
        self.RegisterCno.configure(highlightbackground="#d9d9d9")
        self.RegisterCno.configure(highlightcolor="black")
        self.RegisterCno.configure(insertbackground="black")
        self.RegisterCno.configure(selectbackground="#c4c4c4")
        self.RegisterCno.configure(selectforeground="black")

        self.RegisterAddress = Entry(self.Frame_1)
        self.RegisterAddress.place(relx=0.33, rely=0.54, height=34
                , relwidth=0.54)
        self.RegisterAddress.configure(background="white")
        self.RegisterAddress.configure(disabledforeground="#a3a3a3")
        self.RegisterAddress.configure(font="TkFixedFont")
        self.RegisterAddress.configure(foreground="#000000")
        self.RegisterAddress.configure(highlightbackground="#d9d9d9")
        self.RegisterAddress.configure(highlightcolor="black")
        self.RegisterAddress.configure(insertbackground="black")
        self.RegisterAddress.configure(selectbackground="#c4c4c4")
        self.RegisterAddress.configure(selectforeground="black")

        self.RegisterPassword = Entry(self.Frame_1)
        self.RegisterPassword.place(relx=0.33, rely=0.69, height=34
                , relwidth=0.54)
        self.RegisterPassword.configure(background="white")
        self.RegisterPassword.configure(disabledforeground="#a3a3a3")
        self.RegisterPassword.configure(font="TkFixedFont")
        self.RegisterPassword.configure(foreground="#000000")
        self.RegisterPassword.configure(highlightbackground="#d9d9d9")
        self.RegisterPassword.configure(highlightcolor="black")
        self.RegisterPassword.configure(insertbackground="black")
        self.RegisterPassword.configure(selectbackground="#c4c4c4")
        self.RegisterPassword.configure(selectforeground="black")

        self.Button1 = Button(self.Frame_1)
        self.Button1.place(relx=0.48, rely=0.84, height=33, width=86)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Customer_Register_support.Register_Save)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')
        self.Button1.configure(width=86)






if __name__ == '__main__':
    vp_start_gui()



