#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 26, 2018 12:06:13 AM

import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.customer import ViewOrdered_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = View_Ordered (root)
    ViewOrdered_support.init(root, top)
    root.mainloop()

w = None
def create_View_Ordered(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = View_Ordered (w)
    ViewOrdered_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_View_Ordered():
    global w
    w.destroy()
    w = None

def Hd( g):
    global d
    d = g



class View_Ordered:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 12 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI Black} -size 11 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("923x599+592+140")
        top.title("View_Ordered")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.ViewOrder = Frame(top)
        self.ViewOrder.place(relx=0.01, rely=0.12, relheight=0.73, relwidth=0.98)

        self.ViewOrder.configure(relief=GROOVE)
        self.ViewOrder.configure(borderwidth="10")
        self.ViewOrder.configure(relief=GROOVE)
        self.ViewOrder.configure(background="#c4632b")
        self.ViewOrder.configure(highlightbackground="#d9d9d9")
        self.ViewOrder.configure(highlightcolor="black")
        self.ViewOrder.configure(width=905)
        self.listofstockers()

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.01, rely=0.02, relheight=0.11, relwidth=0.98)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="10")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#c4632b")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=905)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.03, rely=0.31, height=26, width=102)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Name''')

        self.Label1_1 = Label(self.Frame2)
        self.Label1_1.place(relx=0.24, rely=0.31, height=26, width=102)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c4632b")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font10)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''PNO''')

        self.Label1_2 = Label(self.Frame2)
        self.Label1_2.place(relx=0.43, rely=0.31, height=26, width=102)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#c4632b")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font10)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Price''')

        self.Label1_3 = Label(self.Frame2)
        self.Label1_3.place(relx=0.63, rely=0.31, height=26, width=102)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#c4632b")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font10)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Quantity''')

        self.Label1_4 = Label(self.Frame2)
        self.Label1_4.place(relx=0.83, rely=0.31, height=26, width=102)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#c4632b")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font=font10)
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Total''')

        self.Frame3 = Frame(top)
        self.Frame3.place(relx=0.01, rely=0.82, relheight=0.13, relwidth=0.98)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="10")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(background="#c4632b")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")
        self.Frame3.configure(width=905)

        self.Button1 = Button(self.Frame3)
        self.Button1.place(relx=0.03, rely=0.27, height=33, width=156)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=self.Cost)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Total Quantity :''')

        self.TotalQuantity = Label(self.Frame3)
        self.TotalQuantity.place(relx=0.21, rely=0.27, height=26, width=102)
        self.TotalQuantity.configure(activebackground="#f9f9f9")
        self.TotalQuantity.configure(activeforeground="black")
        self.TotalQuantity.configure(background="#c4632b")
        self.TotalQuantity.configure(disabledforeground="#a3a3a3")
        self.TotalQuantity.configure(font=font10)
        self.TotalQuantity.configure(foreground="#000000")
        self.TotalQuantity.configure(highlightbackground="#d9d9d9")
        self.TotalQuantity.configure(highlightcolor="black")

        self.Button1_7 = Button(self.Frame3)
        self.Button1_7.place(relx=0.64, rely=0.27, height=33, width=156)
        self.Button1_7.configure(activebackground="#d9d9d9")
        self.Button1_7.configure(activeforeground="#000000")
        self.Button1_7.configure(background="#d9d9d9")
        self.Button1_7.configure(command=self.Total)
        self.Button1_7.configure(disabledforeground="#a3a3a3")
        self.Button1_7.configure(font=font9)
        self.Button1_7.configure(foreground="#000000")
        self.Button1_7.configure(highlightbackground="#d9d9d9")
        self.Button1_7.configure(highlightcolor="black")
        self.Button1_7.configure(pady="0")
        self.Button1_7.configure(text='''Total Cost :''')

        self.TotalCost = Label(self.Frame3)
        self.TotalCost.place(relx=0.82, rely=0.27, height=26, width=102)
        self.TotalCost.configure(activebackground="#f9f9f9")
        self.TotalCost.configure(activeforeground="black")
        self.TotalCost.configure(background="#c4632b")
        self.TotalCost.configure(disabledforeground="#a3a3a3")
        self.TotalCost.configure(font=font10)
        self.TotalCost.configure(foreground="#000000")
        self.TotalCost.configure(highlightbackground="#d9d9d9")
        self.TotalCost.configure(highlightcolor="black")

    font9 = "-family {Segoe UI Black} -size 11 -weight bold -slant" \
            " italic -underline 0 -overstrike 0"

    def listofstockers(self):
        from firebase import firebase as fb
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/customer/order", None)
        result = fire.get("order", d)
        if result == None:
            messagebox.showinfo("Details", "Order List is Empty")
        else:
            no_of_rows = len(result.keys())
            rows = []
            # for i in range(no_of_rows):
            counter = 0
            for i in result:
                cols = []
                dt = result[i].values()
                val = []
                for x in dt:
                    val.append(x)
                for inner in range(1, 6):
                    l1 = Label(self.ViewOrder, width=19)
                    l1.configure(font=View_Ordered.font9)
                    l1.grid(row=counter, column=inner, sticky=NSEW)
                    l1.configure(text=val[inner - 1])
                    cols.append(l1)
                counter += 1

    def Total(self):
        global g
        g = 0
        from firebase import firebase as fb1
        fire1 = fb1.FirebaseApplication("https://merchant-ca794.firebaseio.com/customer/order", None)
        result1 = fire1.get("order", d)
        for i in result1:
            j = result1[i]["total"]
            g += j
        self.TotalCost.configure(text=g)

    def Cost(self):
        g = 0
        from firebase import firebase as fb2
        fire2 = fb2.FirebaseApplication("https://merchant-ca794.firebaseio.com/customer/order", None)
        result2 = fire2.get("order", d)
        for i in result2:
            j = result2[i]["quantity"]
            g += j
        self.TotalQuantity.configure(text=g)


if __name__ == '__main__':
    vp_start_gui()



