#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 12:00:52 PM


from main.com.nnk.admin import admin
from main.com.nnk.stocker import stocker
from main.com.nnk.dispatcher import dispatcher


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def open_AdminLogin():
    destroy_window()
    admin.vp_start_gui()


def open_StockerLogin():
    destroy_window()
    stocker.vp_start_gui()


def open_DispatcherLogin():
    destroy_window()
    dispatcher.vp_start_gui()


def open_AboutUs():
    pass


if __name__ == '__main__':
    import merchant
    merchant.vp_start_gui()



