#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 07:09:34 PM


import sys
import re
from main.com.nnk.admin import Admin_Home
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def validateAdminLogin():
    print('admin_support.validateAdminLogin')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def validateAdminLogin():
    username = w.adminusername.get()
    password = w.adminpassword.get()
    if username == "":
        messagebox.showerror("Admin Login","Enter the username")
    elif password == "":
        messagebox.showerror("Admin Login","Enter the password")
    else:
        from  firebase import firebase as fb
        fire=fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/admin",None)
        s = fire.get("admin",None)
        if (s['username'] == username and s['password'] == password):
            Admin_Home.vp_start_gui()
        else:
            messagebox.showerror("Admin Login","Username or Password is Invalid")



if __name__ == '__main__':
    import admin
    admin.vp_start_gui()


