#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 12, 2018 05:53:14 PM


import sys
from  main.com.nnk.admin import Admin_Home
from main.com.nnk.admin import Stocker_Registration
from main.com.nnk.admin import Dispatcher_Registration
from  main.com.nnk.admin import admin
from main.com.nnk.stocker import ProductView
from main.com.nnk.admin import Customer_View
from main.com.nnk.admin import SalesView
from main import merchant
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def AdminHome_Dispatcher():
    print('Admin_Home_support.AdminHome_Dispatcher')
    sys.stdout.flush()

def AdminHome_Stocker():
    print('Admin_Home_support.AdminHome_Stocker')
    sys.stdout.flush()

def AdminHome_ViewCustomer():
    print('Admin_Home_support.AdminHome_ViewCustomer')
    sys.stdout.flush()

def AdminHome_ViewProduct():
    print('Admin_Home_support.AdminHome_ViewProduct')
    sys.stdout.flush()

def AdminHome_ViewSales():
    print('Admin_Home_support.AdminHome_ViewSales')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def AdminHome_Stocker():
    destroy_window()
    Stocker_Registration.vp_start_gui()


def AdminHome_Dispatcher():
    destroy_window()
    Dispatcher_Registration.vp_start_gui()


def AdminHome_ViewProduct():
    ProductView.vp_start_gui()


def AdminHome_ViewCustomer():
    Customer_View.vp_start_gui()


def AdminHome_ViewSales():
    SalesView.vp_start_gui()

def AdminHome_Logout():
    destroy_window()
    merchant.vp_start_gui()

if __name__ == '__main__':
    import Admin_Home
    Admin_Home.vp_start_gui()


