#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 15, 2018 06:39:29 PM


import sys
from tkinter import messagebox
from  firebase import firebase as fb
from  main.com.nnk.admin import DispatcherView

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def DispatcherRegistration_Save():
    print('Dispatcher_Registration_support.DispatcherRegistration_Save')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def DispatcherRegistration_Delete():
    id = w.DispatcherRegistrationDelete_Id_.get()
    from firebase import firebase as fb
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher", None)
    result = fire.get("dispatcher", None)
    if id == "":
        messagebox.showerror("Delete Id", "please enter id")
    else:
        if id in result:
            fire.delete("dispatcher", id)
            messagebox.showerror("Delete Id", "id is deleted")
        else:
            messagebox.showerror("Delete Id", "please enter valid id")


def Registration_Id():
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher", None)
    result = fire.get("dispatcher", None)
    if result is None:
        return "1001"
    else:
        for x in result.keys():
            pass
        idno = int(x)
        idno += 1
        return str(idno)


def DispatcherRegistration_Save():
    idno = Registration_Id()
    name = w.DispatcherRegistration_Name.get()
    cno = w.DispatcherRegistration_Contact.get()
    password = w.DispatcherRegistration_Password.get()
    name1 = re.search(r"\w+[a-zA-Z]", name)
    password1 = re.search(r"\w+[a-zA-Z0-9]", password)
    cno1 = re.search(r"\w+[0-9]", cno)
    if name == "":
        messagebox.showerror("Dispatcher Registration", "Please enter the name")
    elif password == "":
        messagebox.showerror("Dispatcher Registration", "Please enter the password")
    elif cno == "":
        messagebox.showerror("Dispatcher Registration", "Please enter the contact no.")
    elif name1 == None:
        messagebox.showerror("Dispatcher Registration", "Please enter proper name")
    elif password1 == None:
        messagebox.showerror("Dispatcher Registration", "Please enter proper password")
    elif cno1 == None:
        messagebox.showerror("Dispatcher Registration", "Please enter proper contact no")
    else:
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/dispatcher", None)
        fire.put("dispatcher", idno, {"name": name, "contact": int(cno), "password": password})
        messagebox.showinfo("Dispatcher Registration", "Information is saved")
        destroy_window()


def DispatcherRegistration_View():
    DispatcherView.vp_start_gui()

if __name__ == '__main__':
    import Dispatcher_Registration
    Dispatcher_Registration.vp_start_gui()


