#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 23, 2018 01:25:41 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.admin import Dispatcher_Registration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Dispatcher_Registration (root)
    Dispatcher_Registration_support.init(root, top)
    root.mainloop()

w = None
def create_Dispatcher_Registration(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Dispatcher_Registration (w)
    Dispatcher_Registration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Dispatcher_Registration():
    global w
    w.destroy()
    w = None


class Dispatcher_Registration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 20 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 13 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font12 = "-family {Segoe UI Black} -size 14 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 0 -overstrike 0"

        top.geometry("694x705+642+150")
        top.title("Dispatcher_Registration")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=695)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.22, rely=0.06, height=46, width=402)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Dispatcher Registration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.12, rely=0.2, height=36, width=142)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Idno :''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.1, rely=0.33, height=36, width=142)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font12)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name :''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.06, rely=0.45, height=36, width=142)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font12)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Contact No :''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.07, rely=0.57, height=36, width=142)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#c4632b")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font12)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Password :''')

        self.DispatcherRegistration_Id_ = Label(self.Frame1)
        self.DispatcherRegistration_Id_.place(relx=0.27, rely=0.2, height=36
                , width=122)
        self.DispatcherRegistration_Id_.configure(activebackground="#f9f9f9")
        self.DispatcherRegistration_Id_.configure(activeforeground="black")
        self.DispatcherRegistration_Id_.configure(background="#c4632b")
        self.DispatcherRegistration_Id_.configure(disabledforeground="#a3a3a3")
        self.DispatcherRegistration_Id_.configure(font=font11)
        self.DispatcherRegistration_Id_.configure(foreground="#000000")
        self.DispatcherRegistration_Id_.configure(highlightbackground="#d9d9d9")
        self.DispatcherRegistration_Id_.configure(highlightcolor="black")
        self.DispatcherRegistration_Id_.configure(text='''.......''')
        idno = Dispatcher_Registration_support.Registration_Id()
        self.DispatcherRegistration_Id_.configure(text=idno)

        self.DispatcherRegistration_Name = Entry(self.Frame1)
        self.DispatcherRegistration_Name.place(relx=0.29, rely=0.33, height=34
                , relwidth=0.45)
        self.DispatcherRegistration_Name.configure(background="white")
        self.DispatcherRegistration_Name.configure(disabledforeground="#a3a3a3")
        self.DispatcherRegistration_Name.configure(font="TkFixedFont")
        self.DispatcherRegistration_Name.configure(foreground="#000000")
        self.DispatcherRegistration_Name.configure(highlightbackground="#d9d9d9")
        self.DispatcherRegistration_Name.configure(highlightcolor="black")
        self.DispatcherRegistration_Name.configure(insertbackground="black")
        self.DispatcherRegistration_Name.configure(selectbackground="#c4c4c4")
        self.DispatcherRegistration_Name.configure(selectforeground="black")

        self.DispatcherRegistration_Contact = Entry(self.Frame1)
        self.DispatcherRegistration_Contact.place(relx=0.29, rely=0.45, height=34
                , relwidth=0.45)
        self.DispatcherRegistration_Contact.configure(background="white")
        self.DispatcherRegistration_Contact.configure(disabledforeground="#a3a3a3")
        self.DispatcherRegistration_Contact.configure(font="TkFixedFont")
        self.DispatcherRegistration_Contact.configure(foreground="#000000")
        self.DispatcherRegistration_Contact.configure(highlightbackground="#d9d9d9")
        self.DispatcherRegistration_Contact.configure(highlightcolor="black")
        self.DispatcherRegistration_Contact.configure(insertbackground="black")
        self.DispatcherRegistration_Contact.configure(selectbackground="#c4c4c4")
        self.DispatcherRegistration_Contact.configure(selectforeground="black")

        self.DispatcherRegistration_Password = Entry(self.Frame1)
        self.DispatcherRegistration_Password.place(relx=0.29, rely=0.57, height=34
                , relwidth=0.45)
        self.DispatcherRegistration_Password.configure(background="white")
        self.DispatcherRegistration_Password.configure(disabledforeground="#a3a3a3")
        self.DispatcherRegistration_Password.configure(font="TkFixedFont")
        self.DispatcherRegistration_Password.configure(foreground="#000000")
        self.DispatcherRegistration_Password.configure(highlightbackground="#d9d9d9")
        self.DispatcherRegistration_Password.configure(highlightcolor="black")
        self.DispatcherRegistration_Password.configure(insertbackground="black")
        self.DispatcherRegistration_Password.configure(selectbackground="#c4c4c4")
        self.DispatcherRegistration_Password.configure(selectforeground="black")
        self.DispatcherRegistration_Password.configure(show="*")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.3, rely=0.67, height=43, width=96)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Dispatcher_Registration_support.DispatcherRegistration_Save)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')

        self.Button1_1 = Button(self.Frame1)
        self.Button1_1.place(relx=0.59, rely=0.67, height=43, width=96)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(command=Dispatcher_Registration_support.DispatcherRegistration_View)
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font9)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''View''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.01, rely=0.75, height=36, width=252)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font12)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Enter idno to delete :''')
        self.Label2_1.configure(width=252)

        self.DispatcherRegistrationDelete_Id_ = Entry(self.Frame1)
        self.DispatcherRegistrationDelete_Id_.place(relx=0.03, rely=0.81
                ,height=34, relwidth=0.45)
        self.DispatcherRegistrationDelete_Id_.configure(background="white")
        self.DispatcherRegistrationDelete_Id_.configure(disabledforeground="#a3a3a3")
        self.DispatcherRegistrationDelete_Id_.configure(font="TkFixedFont")
        self.DispatcherRegistrationDelete_Id_.configure(foreground="#000000")
        self.DispatcherRegistrationDelete_Id_.configure(highlightbackground="#d9d9d9")
        self.DispatcherRegistrationDelete_Id_.configure(highlightcolor="black")
        self.DispatcherRegistrationDelete_Id_.configure(insertbackground="black")
        self.DispatcherRegistrationDelete_Id_.configure(selectbackground="#c4c4c4")
        self.DispatcherRegistrationDelete_Id_.configure(selectforeground="black")


        self.Button1_2 = Button(self.Frame1)
        self.Button1_2.place(relx=0.04, rely=0.88, height=43, width=96)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#d9d9d9")
        self.Button1_2.configure(command=Dispatcher_Registration_support.DispatcherRegistration_Delete)
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font=font9)
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Delete''')






if __name__ == '__main__':
    vp_start_gui()



