#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 27, 2018 03:00:59 PM

import sys
from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.admin import SalesView_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Sales_View (root)
    SalesView_support.init(root, top)
    root.mainloop()

w = None
def create_Sales_View(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Sales_View (w)
    SalesView_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Sales_View():
    global w
    w.destroy()
    w = None


class Sales_View:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI Black} -size 12 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("812x791+650+150")
        top.title("Sales_View")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.View = Frame(top)
        self.View.place(relx=0.01, rely=0.09, relheight=0.9, relwidth=0.97)
        self.View.configure(relief=GROOVE)
        self.View.configure(borderwidth="10")
        self.View.configure(relief=GROOVE)
        self.View.configure(background="#c4632b")
        self.View.configure(highlightbackground="#d9d9d9")
        self.View.configure(highlightcolor="black")
        self.View.configure(width=785)
        self.listofsales()

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.01, rely=0.0, relheight=0.09, relwidth=0.97)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="10")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#c4632b")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=785)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.03, rely=0.4, height=26, width=92)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Name''')

        self.Label1_1 = Label(self.Frame2)
        self.Label1_1.place(relx=0.22, rely=0.4, height=26, width=92)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#c4632b")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font9)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''PNO''')

        self.Label1_2 = Label(self.Frame2)
        self.Label1_2.place(relx=0.42, rely=0.4, height=26, width=92)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#c4632b")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font9)
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Price''')

        self.Label1_3 = Label(self.Frame2)
        self.Label1_3.place(relx=0.62, rely=0.4, height=26, width=92)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#c4632b")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font9)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Quantity''')

        self.Label1_4 = Label(self.Frame2)
        self.Label1_4.place(relx=0.84, rely=0.4, height=26, width=92)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#c4632b")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font=font9)
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Total''')

    font9 = "-family {Segoe UI Black} -size 12 -weight bold -slant" \
            " italic -underline 0 -overstrike 0"

    def listofsales(self):
        from firebase import firebase as fb
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/sales", None)
        result = fire.get("sales", None)
        if result == None:
            messagebox.showinfo("Details", "No Order Available")
        else:
            rows = []
            # for i in range(no_of_rows):
            counter = 0
            for i in result:
                cols = []
                dt = result[i].values()
                val = []
                for x in dt:
                    val.append(x)
                for inner in range(1, 6):
                    l1 = Label(self.View, width=13)
                    l1.configure(font=Sales_View.font9)
                    l1.grid(row=counter, column=inner, sticky=NSEW)
                    l1.configure(background="#c4632b")
                    l1.configure(borderwidth="10")
                    l1.configure(text=val[inner - 1])
                    cols.append(l1)
                counter += 1


if __name__ == '__main__':
    vp_start_gui()



