#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 17, 2018 11:15:44 AM

import sys
from  tkinter import messagebox
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.admin import StockerView_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = StockerRegistration_ViewFrame (root)
    StockerView_support.init(root, top)
    root.mainloop()

w = None
def create_StockerRegistration_ViewFrame(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = StockerRegistration_ViewFrame (w)
    StockerView_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_StockerRegistration_ViewFrame():
    global w
    w.destroy()
    w = None


class StockerRegistration_ViewFrame:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("635x709+650+150")
        top.title("StockerRegistration_ViewFrame")
        top.configure(background="#d9d9d9")



        self.Stocker_View = Frame(top)
        self.Stocker_View.place(relx=0.02, rely=0.01, relheight=0.98
                , relwidth=0.97)
        self.Stocker_View.configure(relief=GROOVE)
        self.Stocker_View.configure(borderwidth="10")
        self.Stocker_View.configure(relief=GROOVE)
        self.Stocker_View.configure(background="#c4632b")
        self.Stocker_View.configure(width=615)
        self.listofstockers()


    font12= "-family {Segoe UI Black} -size 14 -weight bold -slant" \
            " italic -underline 0 -overstrike 0"

    def listofstockers(self):
        from firebase import firebase as fb
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/stocker", None)
        result = fire.get("stocker", None)
        if result == None:
            messagebox.showinfo("Details", "No Stocker Available")
        else:
            no_of_rows = len(result.keys())
            rows = []
            # for i in range(no_of_rows):
            counter = 0
            for i in result:
                cols = []
                l = Label(self.Stocker_View, w, width=16)
                l.configure(font=StockerRegistration_ViewFrame.font12)
                l.grid(row=counter, column=0, sticky=NSEW)
                l.configure(text=i)
                dt = result[i].values()
                val = []
                for x in dt:
                    val.append(x)
                for inner in range(1, 3):
                    l1 = Label(self.Stocker_View, width=16)
                    l1.configure(font=StockerRegistration_ViewFrame.font12)
                    l1.grid(row=counter, column=inner, sticky=NSEW)
                    l1.configure(text=val[inner - 1])
                    cols.append(l1)
                counter += 1
            rows.append(l)

if __name__ == '__main__':
    vp_start_gui()



