#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 12, 2018 07:08:42 PM


import sys
import re
from firebase import firebase as fb
from tkinter import messagebox
from main.com.nnk.admin import StockerView
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def StockerRegistration_Save():
    print('Stocker_Registration_support.StockerRegistration_Save')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def StockerRegistration_Delete():
    id = w.StockerRegistrationDelete_Id.get()
    from firebase import firebase as fb
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/stocker", None)
    result = fire.get("stocker", None)
    if id == "":
        messagebox.showerror("Delete Id", "please enter id")
    else:
        if id in result:
            fire.delete("stocker", id)
            messagebox.showerror("Delete Id", "id is deleted")
        else:
            messagebox.showerror("Delete Id", "please enter valid id")



def StockerRegistration_Id():
    fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/stocker", None)
    result = fire.get("stocker", None)
    if result is None:
        return "101"
    else:
        for x in result.keys():
            pass
        idno = int(x)
        idno += 1
        return str(idno)

def StockerRegistration_Save():
    idno = StockerRegistration_Id()
    name = w.StockerRegistration_Name.get()
    cno = w.StockerRegistration_Contact.get()
    password = w.StockerRegistration_Password.get()
    name1 = re.search(r"\w+[a-zA-Z]",name)
    password1 = re.search(r"\w+[a-zA-Z0-9]",password)
    cno1 = re.search(r"\w+[0-9]",cno)
    if name =="":
        messagebox.showerror("Stocker Registration","Please enter the name")
    elif password =="":
        messagebox.showerror("Stocker Registration", "Please enter the password")
    elif cno =="":
        messagebox.showerror("Stocker Registration", "Please enter the contact no.")
    elif name1 == None:
        messagebox.showerror("Stocker Registration","Please enter proper name")
    elif password1 == None:
        messagebox.showerror("Stocker Registration", "Please enter proper password")
    elif cno1 == None:
        messagebox.showerror("Stocker Registration", "Please enter proper contact no")
    else:
        fire = fb.FirebaseApplication("https://merchant-ca794.firebaseio.com/employee/stocker", None)
        fire.put("stocker", idno, {"name": name, "contact": int(cno), "password": password})
        messagebox.showinfo("Stocker Registration", "Information is saved")
        destroy_window()

def StockerRegistration_View():
    StockerView.vp_start_gui()


if __name__ == '__main__':
    import Stocker_Registration
    Stocker_Registration.vp_start_gui()


