#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 23, 2018 12:46:25 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from main.com.nnk.admin import Stocker_Registration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Stocker_Registration (root)
    Stocker_Registration_support.init(root, top)
    root.mainloop()

w = None
def create_Stocker_Registration(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Stocker_Registration (w)
    Stocker_Registration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Stocker_Registration():
    global w
    w.destroy()
    w = None


class Stocker_Registration:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 13 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Black} -size 14 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI Black} -size 20 -weight bold -slant"  \
            " italic -underline 0 -overstrike 0"

        top.geometry("677x691+650+150")
        top.title("Stocker_Registration")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.01, relwidth=1.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#c4632b")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=675)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.19, rely=0.07, height=46, width=422)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4632b")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Stocker Registration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.09, rely=0.23, height=36, width=152)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#c4632b")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Idno :''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.07, rely=0.32, height=36, width=152)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font11)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name :''')

        self.Label2_2 = Label(self.Frame1)
        self.Label2_2.place(relx=0.03, rely=0.42, height=36, width=152)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#c4632b")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font11)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Contact No :''')

        self.Label2_3 = Label(self.Frame1)
        self.Label2_3.place(relx=0.04, rely=0.5, height=36, width=152)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(background="#c4632b")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(font=font11)
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Password :''')

        self.StockerRegistration_Id = Label(self.Frame1)
        self.StockerRegistration_Id.place(relx=0.25, rely=0.23, height=36
                , width=152)
        self.StockerRegistration_Id.configure(activebackground="#f9f9f9")
        self.StockerRegistration_Id.configure(activeforeground="black")
        self.StockerRegistration_Id.configure(background="#c4632b")
        self.StockerRegistration_Id.configure(disabledforeground="#a3a3a3")
        self.StockerRegistration_Id.configure(font=font10)
        self.StockerRegistration_Id.configure(foreground="#000000")
        self.StockerRegistration_Id.configure(highlightbackground="#d9d9d9")
        self.StockerRegistration_Id.configure(highlightcolor="black")
        self.StockerRegistration_Id.configure(text='''.............''')
        idno = Stocker_Registration_support.StockerRegistration_Id()
        self.StockerRegistration_Id.configure(text=idno)

        self.StockerRegistration_Name = Entry(self.Frame1)
        self.StockerRegistration_Name.place(relx=0.3, rely=0.32, height=34
                , relwidth=0.45)
        self.StockerRegistration_Name.configure(background="white")
        self.StockerRegistration_Name.configure(disabledforeground="#a3a3a3")
        self.StockerRegistration_Name.configure(font="TkFixedFont")
        self.StockerRegistration_Name.configure(foreground="#000000")
        self.StockerRegistration_Name.configure(highlightbackground="#d9d9d9")
        self.StockerRegistration_Name.configure(highlightcolor="black")
        self.StockerRegistration_Name.configure(insertbackground="black")
        self.StockerRegistration_Name.configure(selectbackground="#c4c4c4")
        self.StockerRegistration_Name.configure(selectforeground="black")

        self.StockerRegistration_Contact = Entry(self.Frame1)
        self.StockerRegistration_Contact.place(relx=0.3, rely=0.42, height=34
                , relwidth=0.45)
        self.StockerRegistration_Contact.configure(background="white")
        self.StockerRegistration_Contact.configure(disabledforeground="#a3a3a3")
        self.StockerRegistration_Contact.configure(font="TkFixedFont")
        self.StockerRegistration_Contact.configure(foreground="#000000")
        self.StockerRegistration_Contact.configure(highlightbackground="#d9d9d9")
        self.StockerRegistration_Contact.configure(highlightcolor="black")
        self.StockerRegistration_Contact.configure(insertbackground="black")
        self.StockerRegistration_Contact.configure(selectbackground="#c4c4c4")
        self.StockerRegistration_Contact.configure(selectforeground="black")

        self.StockerRegistration_Password = Entry(self.Frame1)
        self.StockerRegistration_Password.place(relx=0.3, rely=0.5, height=34
                , relwidth=0.45)
        self.StockerRegistration_Password.configure(background="white")
        self.StockerRegistration_Password.configure(disabledforeground="#a3a3a3")
        self.StockerRegistration_Password.configure(font="TkFixedFont")
        self.StockerRegistration_Password.configure(foreground="#000000")
        self.StockerRegistration_Password.configure(highlightbackground="#d9d9d9")
        self.StockerRegistration_Password.configure(highlightcolor="black")
        self.StockerRegistration_Password.configure(insertbackground="black")
        self.StockerRegistration_Password.configure(selectbackground="#c4c4c4")
        self.StockerRegistration_Password.configure(selectforeground="black")
        self.StockerRegistration_Password.configure(show="*")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.3, rely=0.6, height=43, width=106)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Stocker_Registration_support.StockerRegistration_Save)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')

        self.Button1_1 = Button(self.Frame1)
        self.Button1_1.place(relx=0.58, rely=0.6, height=43, width=106)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(command=Stocker_Registration_support.StockerRegistration_View)
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font11)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''View''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.01, rely=0.72, height=26, width=272)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#c4632b")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font11)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Enter id no to delete :''')
        self.Label2_1.configure(width=272)

        self.Button1_2 = Button(self.Frame1)
        self.Button1_2.place(relx=0.06, rely=0.86, height=43, width=86)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#d9d9d9")
        self.Button1_2.configure(command=Stocker_Registration_support.StockerRegistration_Delete)
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font=font11)
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Delete''')
        self.Button1_2.configure(width=86)

        self.StockerRegistrationDelete_Id = Entry(self.Frame1)
        self.StockerRegistrationDelete_Id.place(relx=0.04, rely=0.78, height=34
                , relwidth=0.39)
        self.StockerRegistrationDelete_Id.configure(background="white")
        self.StockerRegistrationDelete_Id.configure(disabledforeground="#a3a3a3")
        self.StockerRegistrationDelete_Id.configure(font="TkFixedFont")
        self.StockerRegistrationDelete_Id.configure(foreground="#000000")
        self.StockerRegistrationDelete_Id.configure(insertbackground="black")
        self.StockerRegistrationDelete_Id.configure(width=264)






if __name__ == '__main__':
    vp_start_gui()



